services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=lmaodead
      - POSTGRES_PASSWORD=lmaodead
      - POSTGRES_DB=metricsdb